security:
    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                property: apiKey
    role_hierarchy:
            ROLE_ADMIN: [ROLE_API]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: true
            provider: user_db_provider
        api:
            pattern: ^/api/
#            guard:
#                authenticators:
#                   - App\Security\TokenAuthenticator
            provider: user_db_provider
    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/admin/, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost: 12